# Generated by Django 6.0.5 on 2026-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackets',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rackets',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rackets',
            name='type',
            field=models.CharField(choices=[('Y', 'YONEX'), ('D', 'DEEP'), ('B', 'BOULT'), ('S', 'SAMSH')], max_length=2),
        ),
    ]
