# Generated by Django 6.0.5 on 2026-05-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBL', '0002_rackets_description_rackets_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackets',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rackets',
            name='type',
            field=models.CharField(choices=[('B', 'BOULT'), ('Y', 'YONEX'), ('D', 'DEEP'), ('S', 'SAMSH')], max_length=2),
        ),
    ]
