# Generated by Django 6.0.5 on 2026-05-17 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBL', '0003_alter_rackets_pricing_alter_rackets_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackets',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='rackets',
            name='type',
            field=models.CharField(choices=[('S', 'SAMSH'), ('D', 'DEEP'), ('B', 'BOULT'), ('Y', 'YONEX')], max_length=2),
        ),
        migrations.CreateModel(
            name='LaserSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(max_length=30, unique=True)),
                ('warranty_months', models.PositiveSmallIntegerField(default=12)),
                ('racket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='DBL.rackets')),
            ],
        ),
        migrations.CreateModel(
            name='racket_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5)),
                ('racket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='DBL.rackets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='racket_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='', max_length=200)),
                ('rackets', models.ManyToManyField(related_name='types', to='DBL.rackets')),
            ],
        ),
    ]
