# Generated by Django 6.0.5 on 2026-05-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBL', '0004_alter_rackets_pricing_alter_rackets_type_laserserial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackets',
            name='type',
            field=models.CharField(choices=[('Y', 'YONEX'), ('B', 'BOULT'), ('S', 'SAMSH'), ('D', 'DEEP')], max_length=2),
        ),
    ]
